name: Docker-Update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
        cp .env.sample .env.local && \
        sed -i 's/GH_TOKEN=.*/GH_TOKEN=\"${{ secrets.GH_TOKEN }}\"/' .env.local && \
        sed -i 's/RESEND_TOKEN=.*/RESEND_TOKEN=\"${{ secrets.RESEND_TOKEN }}\"/' .env.local && \
        sed -i 's/RESEND_RECEIVER=.*/RESEND_RECEIVER=\"${{ secrets.RESEND_RECEIVER }}\"/' .env.local && \
        cat .env
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        file: ".docker/deployment/react/frontend/Dockerfile"
        context: "."
        platforms: linux/arm64
        push: true
        tags: swondi/franky-portfolio:latest